export const PRODUCTS = [
    {
        id: "1",
        name: "Hass Avocados",
        rating: 4.9,
        reviews: 324,
        description: "Sustainably sourced, shade-grown avocados rich in healthy fats. Our avocados offer a creamy, nutty flavor with no bitterness. Perfect for traditional guacamole or modern toast toppings.",
        details: "Approx. 1kg pack",
        price: 520,
        originalPrice: null,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuBsuSzVBMy55YONEPobR9CudTnOrGyrMOPWv86lDnCu6SbYZhrSd0CwlasU49ZZimFWsaO9dGVo-6r3FYsLx4ofB-mixgVO6VIDu4qUq6mFdegjKrYbgFdYX0t0oNftEri_qrotHxAEYcT30MqgnzqNkzJt0Y_WlKmVu8LXRCjYLrYoq4zOATze71NHKV9pHT92u-Ky0V0PnXq94DunqPinLRes88XNaaSMVnF9NfXHxY3raRLm4wf5LYQHbuql8MQhk01wNAIWMBg",
        badge: "Best Seller",
        category: "Fresh Produce",
        badgeColor: "bg-primary text-background-dark",
        attributes: [
            { label: "Origin", value: "India", icon: "public" },
            { label: "Certification", value: "Organic Certified", icon: "eco" },
            { label: "Shipping", value: "Free over ₹1000", icon: "local_shipping" },
            { label: "Guarantee", value: "Freshness Guaranteed", icon: "verified" },
        ]
    },
    {
        id: "2",
        name: "Vine Tomatoes",
        rating: 4.5,
        reviews: 128,
        description: "Bursting with flavor, these vine-ripened tomatoes are pesticide-free and harvested at peak ripeness. Perfect for salads, sauces, or roasting.",
        details: "500g punnet",
        price: 340,
        originalPrice: null,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuDYrk4hqklDDLvRxMoKPns6-Izqt51viC8mnXjAFsWuzwTrOaj3fM-Xxa5WxwCMvoRTxCfE6rh_QI7dUK_CD21aJg2bqjCPyi42rHfBRyYhWhrPa67pmV4mLnWJTcH9xIFdL8i_py-qjguyNu7H5ExigFuCOUDfP-d65Vm3D_rJuKOEn-Th9hBpUI9PENKdGcLsY3PtHE_7-ncvpoaIsSZx8o3LqiyVSw8a-ST2w-bv1bBHEXbtbOVjqZ7z9cWCSxZ2CbD_I8JaAto",
        badge: null,
        category: "Fresh Produce",
        badgeColor: null,
        attributes: [
            { label: "Origin", value: "Local Farm", icon: "public" },
            { label: "Certification", value: "Pesticide Free", icon: "eco" },
            { label: "Shipping", value: "Next Day Delivery", icon: "local_shipping" },
            { label: "Guarantee", value: "Fresh Arrival", icon: "verified" },
        ]
    },
    {
        id: "3",
        name: "Raw Almonds",
        rating: 5.0,
        reviews: 86,
        description: "Crunchy, unpasteurized, and full of natural goodness. Our raw almonds are an excellent source of protein, fiber, and healthy fats.",
        details: "250g bag",
        price: 790,
        originalPrice: null,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCFkNZan8Qr_v0eKgBTvA4SYhRMNgIef-BCVdGqpcWGYz2kuSrCMIkBHKfZnlwNnub4CnR1r0sI4VsKA2OooGL3kNWq0vwZFsh08EB9NBqgvjTYdqoRNkEjm8Asi85lK6T8i1UfE8B3jzea2FFsTw3qMpBkU1pSKESk8Gn0GfKFw3nfe5azDldsa6lZBksL4kiByRTDghw7Hz3ayuy-PXwiMmjShCvwyiFH6EvEinUA1P3n2HIbBFNKOXAp-wCD72px5sO2vb4safM",
        badge: null,
        category: "Pantry Staples",
        badgeColor: null,
        attributes: [
            { label: "Origin", value: "California, USA", icon: "public" },
            { label: "Certification", value: "Non-GMO", icon: "eco" },
            { label: "Shipping", value: "Standard", icon: "local_shipping" },
            { label: "Guarantee", value: "Quality Check", icon: "verified" },
        ]
    },
    {
        id: "4",
        name: "Extra Virgin Olive Oil",
        rating: 4.8,
        reviews: 210,
        description: "Cold-pressed from hand-picked olives, this premium oil has a rich aroma and a peppery finish. Ideal for drizzling over salads or dipping bread.",
        details: "500ml bottle",
        price: 1160,
        originalPrice: 1440,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuAq8tGWmVJ40Gzv1ZoVWWdRUPFVvsOE1Ds3rR2sOya1eMnlSPFMO0YBsQjJcNCrhvrw0IcPO0E6TeLBMwRfby44nzXb6oYFHpFEKuKHynE1_HJYUqGtrKyJSRiyzRQM37knrsZI2zDq8P96VjQQalTEqWOQyH7qL5qX22H5kBtFf9SCcUelYXHedhWqtxfI0Rqqn3FiTEszuUqgcjgp-KbkBa4iRUYdCQipmR3DRxARVFxUugTgPKr8em8J2_2_PHL2BHNJopLfiMI",
        badge: "Sale",
        category: "Oils & Vinegars",
        badgeColor: "bg-[#e85d30] text-white",
        attributes: [
            { label: "Origin", value: "Italy", icon: "public" },
            { label: "Certification", value: "Cold Pressed", icon: "eco" },
            { label: "Shipping", value: "Secure Packed", icon: "local_shipping" },
            { label: "Guarantee", value: "Authentic", icon: "verified" },
        ]
    },
    {
        id: "5",
        name: "Sweet Strawberries",
        rating: 4.7,
        reviews: 145,
        description: "Juicy, sweet, and locally grown without harmful chemicals. These strawberries are picked fresh daily to ensure maximum flavor.",
        details: "250g punnet",
        price: 470,
        originalPrice: null,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuCT7X6Aha2KYYM21PPtYpyJDvMROwNU3LzI8doaA_KhMdyomaRstVjt4-U3HmtgOfLl8e1pbPb_ln00How20geq9L52YYWzo0FWCj_G9Xse5NUGIl9hiLday-uSKIwduHu9mHFmpKuNm1I2-NOjg4j3R-4E0zJ0hJJ8Vmqn_U2OUfDL3p85IHGOXtDsCZUfnmnLIFE64aM75n9wKioBrFnebupJt_C0Y5Vtai-gq3KP_-JIVBRWagKgFvU4DwHiel9uf6E2fY3__As",
        badge: "Local",
        category: "Fresh Produce",
        badgeColor: "bg-primary text-[#111814]",
        attributes: [
            { label: "Origin", value: "Local", icon: "public" },
            { label: "Certification", value: "Seasonal", icon: "eco" },
            { label: "Shipping", value: "Same Day", icon: "local_shipping" },
            { label: "Guarantee", value: "Freshness", icon: "verified" },
        ]
    },
    {
        id: "6",
        name: "Artisan Sourdough",
        rating: 4.9,
        reviews: 89,
        description: "Traditionally fermented for 48 hours, our sourdough has a crispy crust and a chewy, airy interior. Baked fresh every morning.",
        details: "Per Loaf",
        price: 560,
        originalPrice: null,
        image: "https://lh3.googleusercontent.com/aida-public/AB6AXuA_3Wd8BKT5IzxyXvBlgtYUzXkf3qah6H0943Czp8vITtgMi3D8_1LUpo4qi6Tno5NMDdeKuuvhSxxp0LBMGA9LgnX8w-frCirLQ-YUYM5xFtArE8FyBVqfiYTG-NF4Pa8mO28wirxTkVM9c9CBmr5Mt17p6jCyajc-BRjqs6TKRyWTBlBk0B3tPaBXR4hDA8sKSn_KaQd7-dH_VI4q5k_SoU0aC9DrRqB5MxuTsBXW3-YlR_EMl5UQhJSkmETSiIMalgabZX3CsbE",
        badge: null,
        category: "Pantry Staples",
        badgeColor: null,
        outOfStock: true,
        attributes: [
            { label: "Origin", value: "Bakery", icon: "public" },
            { label: "Certification", value: "Handmade", icon: "eco" },
            { label: "Shipping", value: "Fragile", icon: "local_shipping" },
            { label: "Guarantee", value: "Baked Today", icon: "verified" },
        ]
    },
    {
        id: "7",
        name: "Organic Honey",
        rating: 4.8,
        reviews: 56,
        description: "Pure, raw, and unfiltered honey from organic wildflower meadows. Rich in antioxidants and natural enzymes.",
        details: "500g Jar",
        price: 850,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800",
        badge: "Pure",
        category: "Pantry Staples",
        badgeColor: "bg-yellow-500 text-black",
        attributes: [
            { label: "Origin", value: "Wildflower Meadows", icon: "public" },
            { label: "Certification", value: "Raw & Unfiltered", icon: "eco" },
            { label: "Shipping", value: "Glass Safe", icon: "local_shipping" },
            { label: "Guarantee", value: "Pure", icon: "verified" },
        ]
    },
    {
        id: "8",
        name: "Kale Bunch",
        rating: 4.6,
        reviews: 34,
        description: "Packed with vitamins and nutrients, our organic kale is crisp and tender. Great for salads, smoothies, or baking into chips.",
        details: "Organic Bunch",
        price: 180,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1524179091875-bf99a9a6af57?auto=format&fit=crop&q=80&w=800",
        badge: "Fresh",
        category: "Fresh Produce",
        badgeColor: "bg-primary text-[#111814]",
        attributes: [
            { label: "Origin", value: "Local Farm", icon: "public" },
            { label: "Certification", value: "Pesticide Free", icon: "eco" },
            { label: "Shipping", value: "Chilled", icon: "local_shipping" },
            { label: "Guarantee", value: "Freshness", icon: "verified" },
        ]
    },
    {
        id: "9",
        name: "Organic Quinoa",
        rating: 4.8,
        description: "500g Pack",
        price: 380,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=800",
        badge: "Superfood",
        category: "Pantry Staples",
        badgeColor: "bg-[#ffd700] text-black"
    },
    {
        id: "10",
        name: "Balsamic Vinegar",
        rating: 4.7,
        description: "250ml Aged",
        price: 890,
        originalPrice: 1100,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
        badge: "Aged",
        category: "Oils & Vinegars",
        badgeColor: "bg-[#5c3a21] text-white"
    },
    {
        id: "11",
        name: "Dried Mango",
        rating: 4.9,
        description: "200g Pack",
        price: 450,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1606775577665-22a3eb5555d4?auto=format&fit=crop&q=80&w=800",
        badge: null,
        category: "Organic Snacks",
        badgeColor: null
    },
    {
        id: "12",
        name: "Bamboo Dish Brush",
        rating: 4.5,
        description: "Eco-friendly",
        price: 220,
        originalPrice: null,
        image: "https://images.unsplash.com/photo-1584622050111-993a426fbf0a?auto=format&fit=crop&q=80&w=800",
        badge: "Eco",
        category: "Home Goods",
        badgeColor: "bg-[#2d4035] text-white"
    }
];

export const CATEGORIES = [
    "All",
    "Fresh Produce",
    "Pantry Staples",
    "Oils & Vinegars",
    "Organic Snacks",
    "Home Goods"
];
